apiVersion: v1
kind: Service
metadata:
  name: {{ include "oscal-report-generator.fullname" . }}
  labels:
    {{- include "oscal-report-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  selector:
    {{- include "oscal-report-generator.selectorLabels" . | nindent 4 }}
